load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cu",
    srcs = ["cu.go"],
    importpath = "github.com/jumpsiegel/radiance/pkg/sbf/cu",
    visibility = ["//visibility:public"],
)
