load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "archiveutil",
    srcs = ["archiveutil.go"],
    importpath = "github.com/jumpsiegel/radiance/pkg/archiveutil",
    visibility = ["//visibility:public"],
)
