load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "netlink",
    srcs = ["interfaces.go"],
    importpath = "github.com/jumpsiegel/radiance/pkg/netlink",
    visibility = ["//visibility:public"],
)
